  using Hilma.Domain.Attributes;

namespace Hilma.Domain.DataContracts
{
    /// <summary>
    ///     Error or warning generated by TED about a notice.
    /// </summary>
    [Contract]
    public class TedValidationItem
    {
        /// <summary>
        ///     TED assigned magic string that might identify where the error is or not.
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        ///     If the item is accepted or not, despite the validation item.
        /// </summary>
        public bool Valid { get; set; }
        /// <summary>
        ///     How severe the error or warning is.
        /// </summary>
        public string Severity { get; set; }
        /// <summary>
        ///     Free text description of the problem.
        /// </summary>
        public string Message { get; set; }
        /// <summary>
        ///     Stack trace type of details of the problem.
        /// </summary>
        public string Details { get; set; }
    }
}
